/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esquemasypantallas;

import clases.*;
import controlador.ControlTorneo;
import esquemasypantallas.frmInternal.frmInTor;
import esquemasypantallas.frmInternal.frmModTor;
import formulariosNO_USAR.frmTorneos;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class frmVisorTorneos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVisorTorneos
     */
    public frmVisorTorneos() {
        initComponents();
        ControlTorneo ct = new ControlTorneo();
        tabla(ct.show());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnNewTorneo = new javax.swing.JButton();
        jBtnMostrarDet = new javax.swing.JButton();
        jBtnAutorizar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxtFiltro1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JRbnInicio = new javax.swing.JRadioButton();
        JRbnFin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtFechaInicio = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFechaFin = new javax.swing.JFormattedTextField();
        jBtnAct = new javax.swing.JButton();
        jBtnApp = new javax.swing.JButton();
        jBtnMod = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torneo", "Fecha Inicio", "Fecha Fin", "Estado", "Campeon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jBtnNewTorneo.setText("Crear Nuevo Torneo");
        jBtnNewTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNewTorneoMouseClicked(evt);
            }
        });

        jBtnMostrarDet.setText("Mostrar Detalles");
        jBtnMostrarDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnMostrarDetMouseClicked(evt);
            }
        });

        jBtnAutorizar.setText("Autorizar Torneo");
        jBtnAutorizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAutorizarMouseClicked(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseClicked(evt);
            }
        });

        jTxtFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFiltro1KeyTyped(evt);
            }
        });

        jLabel1.setText("Filtrar Busqueda");

        jLabel2.setText("Por nombre, estado o campeón");

        buttonGroup1.add(JRbnInicio);
        JRbnInicio.setSelected(true);
        JRbnInicio.setText("Fecha Inicio");

        buttonGroup1.add(JRbnFin);
        JRbnFin.setText("Fecha Fin");

        jLabel3.setText("Por Rango de Fecha");

        try {
            jTxtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("De");

        jLabel5.setText("Hasta");

        try {
            jTxtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBtnAct.setText("Actualizar Tabla");
        jBtnAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnActMouseClicked(evt);
            }
        });

        jBtnApp.setText("Aplicar");
        jBtnApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRbnFin)
                            .addComponent(JRbnInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(jBtnAct)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnApp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAct)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTxtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jBtnApp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JRbnInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JRbnFin))
                            .addComponent(jTxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11))))
        );

        jBtnMod.setText("Modificar");
        jBtnMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnModMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBtnNewTorneo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnMostrarDet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAutorizar)
                        .addGap(204, 204, 204))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNewTorneo)
                    .addComponent(jBtnMostrarDet)
                    .addComponent(jBtnAutorizar)
                    .addComponent(jBtnEliminar)
                    .addComponent(jBtnMod))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMostrarDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMostrarDetMouseClicked
        // TODO add your handling code here:
          
        
        int indext= this.jTable1.getSelectedRow();
        int indexm = this.jTable1.convertRowIndexToModel(indext);
        if( indexm != -1){
      frmDetalleTorneo obj = new frmDetalleTorneo((Torneo) this.jTable1.getValueAt(indext, 0));
        JDesktopPane pane =getDesktopPane();
        pane.add(obj);
        obj.setVisible(true);
        
        }
    }//GEN-LAST:event_jBtnMostrarDetMouseClicked

    private void jBtnNewTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNewTorneoMouseClicked
      
        Utilidades util = new Utilidades();
        JDesktopPane pane = getDesktopPane();
        frmInTor obj = new frmInTor();
        util.openForm(obj, pane);
        
        
        
    }//GEN-LAST:event_jBtnNewTorneoMouseClicked

    private void jBtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarMouseClicked
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_jBtnEliminarMouseClicked

    private void jBtnActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnActMouseClicked
        // TODO add your handling code here:
        ControlTorneo ct = new ControlTorneo();
        tabla(ct.show());
    }//GEN-LAST:event_jBtnActMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int index = this.jTable1.getSelectedRow();
        Torneo tr = (Torneo) this.jTable1.getValueAt(index,0);
        if (tr.getTorEstado().equals("Pendiente")) {
            this.jBtnMod.setText("Modificar");
        }
         if (tr.getTorEstado().equals("Curso")){
        this.jBtnMod.setText("Cambiar Estado");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBtnModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModMouseClicked
        // TODO add your handling code here:
        
        mod();
    }//GEN-LAST:event_jBtnModMouseClicked

    private void jTxtFiltro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFiltro1KeyTyped
        // TODO add your handling code here:
        filtrarNom();
    }//GEN-LAST:event_jTxtFiltro1KeyTyped

    private void jBtnAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAppMouseClicked
        // TODO add your handling code here:
        filtrarNom();
    }//GEN-LAST:event_jBtnAppMouseClicked

    private void jBtnAutorizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAutorizarMouseClicked
      
        autorizar();
    }//GEN-LAST:event_jBtnAutorizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRbnFin;
    private javax.swing.JRadioButton JRbnInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAct;
    private javax.swing.JButton jBtnApp;
    private javax.swing.JButton jBtnAutorizar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnMod;
    private javax.swing.JButton jBtnMostrarDet;
    private javax.swing.JButton jBtnNewTorneo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jTxtFechaFin;
    private javax.swing.JFormattedTextField jTxtFechaInicio;
    private javax.swing.JTextField jTxtFiltro1;
    // End of variables declaration//GEN-END:variables

    
    public void tabla(ArrayList<Torneo> tr){
         String [] columnas = {"Torneo","Fecha Inicio","Fecha Fin","Estado","Campeon"};
    DefaultTableModel tb = new DefaultTableModel(null,columnas);
    Object[] obj = new Object[6];
        for (int i = 0; i < tr.size(); i++) {
            obj[0] = tr.get(i);
            obj[1] = tr.get(i).getFechaInicio();
            obj[2] = tr.get(i).getFechaFin();
            obj[3] = tr.get(i).getTorEstado();
            obj[4] = tr.get(i).getCampeon();
            tb.addRow(obj);
        }
        this.jTable1.setModel(tb);
    }


   public void eliminar(){
   int index = this.jTable1.getSelectedRow();

       if (index != -1) {
           
                int o = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar este torneo?!","Eliminar Torneo",JOptionPane.YES_NO_OPTION);
           if (o == 0) {
               ControlTorneo cr = new ControlTorneo();
               JOptionPane.showMessageDialog(rootPane, cr.delete(this.jTable1.getValueAt(index, 0)),"Confirmación",JOptionPane.INFORMATION_MESSAGE);
           }
           
           
       }
   
   }
   
   public void mod(){
   
   int i = this.jTable1.getSelectedRow();
      
       if (i != -1) {
           
           
           Torneo tr = (Torneo) this.jTable1.getValueAt(i, 0);
           if (tr.getTorEstado().equals("Pendiente")) {
           frmModTor frm = new frmModTor(tr);
           JDesktopPane pane = getDesktopPane();
           pane.add(frm);
           frm.setVisible(true);
           }
       }
   
   }
   
   public void filtrarNom(){
   
       ControlTorneo ct = new ControlTorneo();
       String combo = "";
       if (this.JRbnInicio.isSelected()) {
           combo ="torFechIni";
       }else{
       combo ="torFechFin";
       }
       tabla(ct.filtrar(this.jTxtFiltro1.getText(),combo,this.jTxtFechaInicio.getText(),this.jTxtFechaFin.getText()));
   }
   
   public void autorizar(){
     int index = this.jTable1.getSelectedRow();
     Torneo tr = (Torneo) this.jTable1.getValueAt(index, 0);
        if (index != -1) {
            
            if (tr.getTorEstado().equals("Pendiente")) {
                         ControlTorneo ct = new ControlTorneo();
        int o = JOptionPane.showConfirmDialog(rootPane, "Desea autorizar este torneo?(se generarán los partidos de la primera jornada)","Autorixar Torneo",JOptionPane.YES_NO_OPTION);
       
   
        if (o== 0) {
            String autorizarTorneo = ct.autorizarTorneo((Torneo) this.jTable1.getValueAt(index, 0));
        JOptionPane.showMessageDialog(rootPane, autorizarTorneo);
        } 
            }else{
            JOptionPane.showMessageDialog(rootPane, "Solo puede autorizarse torneos en estado 'Pendiente'","Advertencia!",JOptionPane.WARNING_MESSAGE);
            }
     
        }
     
   }
}
