/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package NO_USAR;

import clases.Incidencia;
import clases.Partido;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class frmResPartido extends javax.swing.JFrame {

    /**
     * Creates new form frmResPartido
     */
    public frmResPartido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtHoraInicio = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtJornada = new javax.swing.JTextField();
        jTxtHoraFin = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtELocal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocal = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtMinLocal = new javax.swing.JFormattedTextField();
        jCmbIncLocal = new javax.swing.JComboBox();
        jTxtJugLocal = new javax.swing.JTextField();
        jCmbTiempoLocal = new javax.swing.JComboBox();
        jBtnEliminarLocal = new javax.swing.JButton();
        jBtnAgregarLocal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTxtEVisita = new javax.swing.JTextField();
        jTxtJugVisita = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtMinVisita = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVisitante = new javax.swing.JTable();
        jCmbIncVisita = new javax.swing.JComboBox();
        jBtnAgregarVisita = new javax.swing.JButton();
        jBtnEliminarVisita = new javax.swing.JButton();
        jCmbTiempoVisita = new javax.swing.JComboBox();
        jBtnModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBtnAgregarJugador = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jTxtHoraInicio.setText("08:30 AM");

        jLabel1.setText("Fecha");

        jLabel2.setText("Hora inicio");

        try {
            jTxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtFecha.setText("25/11/2017");

        jLabel11.setText("Jornada");

        jTxtJornada.setText("Primera");
        jTxtJornada.setEnabled(false);

        jTxtHoraFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jTxtHoraFin.setText("10:30 AM");

        jLabel12.setText("Hora fin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtJornada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTxtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel3.setText("Local");

        jTxtELocal.setText("EquipoLocal");
        jTxtELocal.setEnabled(false);

        jTableLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Tipo", "Minuto", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLocal);
        if (jTableLocal.getColumnModel().getColumnCount() > 0) {
            jTableLocal.getColumnModel().getColumn(0).setResizable(false);
            jTableLocal.getColumnModel().getColumn(1).setResizable(false);
            jTableLocal.getColumnModel().getColumn(2).setResizable(false);
            jTableLocal.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("Jugador");

        jLabel6.setText("Incidencia");

        jLabel7.setText("Minuto");

        try {
            jTxtMinLocal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtMinLocal.setText("33:45");

        jCmbIncLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Gol de penalti", "Autogol", "Gol olímpico", "Gol libre directo", "Asistencia", "Penalti", "Corner", "Tarjeta Roja", "Tarjeta Amarilla" }));

        jTxtJugLocal.setText("Fulano");
        jTxtJugLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtJugLocalKeyTyped(evt);
            }
        });

        jCmbTiempoLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Primer tiempo", "Segundo Tiempo", "Tiempo Extra" }));

        jBtnEliminarLocal.setText("Eliminar");
        jBtnEliminarLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarLocalMouseClicked(evt);
            }
        });

        jBtnAgregarLocal.setText("Agregar");
        jBtnAgregarLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarLocalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtJugLocal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCmbIncLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtELocal)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTxtMinLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCmbTiempoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAgregarLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEliminarLocal)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtELocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtJugLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCmbIncLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtMinLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbTiempoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarLocal)
                    .addComponent(jBtnEliminarLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setText("Visitante");

        jTxtEVisita.setText("EquipoVisita");
        jTxtEVisita.setEnabled(false);

        jTxtJugVisita.setText("Sutano");

        jLabel8.setText("Jugador");

        jLabel9.setText("Incidencia");

        jLabel10.setText("Minuto");

        try {
            jTxtMinVisita.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtMinVisita.setText("15:03");

        jTableVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Tipo", "Minuto", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVisitante);
        if (jTableVisitante.getColumnModel().getColumnCount() > 0) {
            jTableVisitante.getColumnModel().getColumn(0).setResizable(false);
            jTableVisitante.getColumnModel().getColumn(1).setResizable(false);
            jTableVisitante.getColumnModel().getColumn(2).setResizable(false);
            jTableVisitante.getColumnModel().getColumn(3).setResizable(false);
        }

        jCmbIncVisita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Gol de penalti", "Autogol", "Gol olímpico", "Gol libre directo", "Asistencia", "Penalti", "Corner", "Tarjeta Roja", "Tarjeta Amarilla" }));

        jBtnAgregarVisita.setText("Agregar");
        jBtnAgregarVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarVisitaMouseClicked(evt);
            }
        });

        jBtnEliminarVisita.setText("Eliminar");
        jBtnEliminarVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarVisitaMouseClicked(evt);
            }
        });

        jCmbTiempoVisita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Primer tiempo", "Segundo Tiempo", "Tiempo Extra" }));

        jBtnModificar.setText("Modificar Resultado");

        jButton1.setText("Mostrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTxtMinVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbTiempoVisita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTxtEVisita)
                            .addComponent(jTxtJugVisita, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCmbIncVisita, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAgregarVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEliminarVisita)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBtnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtEVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtJugVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCmbIncVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtMinVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbTiempoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarVisita)
                    .addComponent(jBtnEliminarVisita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnModificar)
                    .addComponent(jButton1)))
        );

        jBtnAgregarJugador.setText("Agregar Resultado");
        jBtnAgregarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarJugadorMouseClicked(evt);
            }
        });

        jBtnLimpiar.setText("Limpiar Campos");
        jBtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAgregarJugador))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnAgregarJugador)
                            .addComponent(jBtnLimpiar)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarLocalMouseClicked
        // TODO add your handling code here:
         if(validar(jTxtJugLocal,jCmbIncLocal,jTxtMinLocal,jCmbTiempoLocal)){
             if(alreadyInTable(jTxtJugLocal.getText()+this.jTxtMinLocal.getText()+this.jCmbTiempoLocal.getSelectedItem().toString(),this.jTableLocal)){
             agregarTabla(jTxtJugLocal.getText(),jCmbIncLocal.getSelectedItem().toString(),jTxtMinLocal.getText(),this.jCmbTiempoLocal.getSelectedItem().toString(),this.jTableLocal);
             limpiar(jTxtJugLocal,jCmbIncLocal,jTxtMinLocal,jCmbTiempoLocal);
             }
         }
        
        
    }//GEN-LAST:event_jBtnAgregarLocalMouseClicked

    private void jBtnEliminarLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarLocalMouseClicked
        // TODO add your handling code here:
        int index = jTableLocal.getSelectedRow();
        eliminarTabla(index,this.jTableLocal);
        
    }//GEN-LAST:event_jBtnEliminarLocalMouseClicked

    private void jBtnAgregarVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarVisitaMouseClicked
        // TODO add your handling code here:
        if(validar(jTxtJugVisita,jCmbIncVisita,jTxtMinVisita,jCmbTiempoVisita)){
             if(alreadyInTable(jTxtJugVisita.getText()+this.jTxtMinVisita.getText()+this.jCmbTiempoVisita.getSelectedItem().toString(),this.jTableVisitante)){
             agregarTabla(jTxtJugVisita.getText(),jCmbIncVisita.getSelectedItem().toString(),jTxtMinVisita.getText(),this.jCmbTiempoVisita.getSelectedItem().toString(),this.jTableVisitante);
             limpiar(jTxtJugVisita,jCmbIncVisita,jTxtMinVisita,jCmbTiempoVisita);
             }
         }
        
        
        //agregarTabla(jTxtJugVisita.getText(), jCmbIncVisita.getSelectedItem().toString(), jTxtMinVisita.getText(),jCmbIncVisita.getSelectedItem().toString(),jTableVisitante);
    }//GEN-LAST:event_jBtnAgregarVisitaMouseClicked

    private void jBtnEliminarVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarVisitaMouseClicked
        // TODO add your handling code here:
        int index = jTableVisitante.getSelectedRow();
        eliminarTabla(index, jTableVisitante);
    }//GEN-LAST:event_jBtnEliminarVisitaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableLocal.getModel();
        int size = model.getRowCount();
        String [] cont = new String[size];
        for(int i =0; i< size; i++){
            cont[i] = model.getValueAt(i, 0).toString() + model.getValueAt(i, 1).toString() +
            model.getValueAt(i, 2).toString();

        }
        JOptionPane.showMessageDialog(rootPane, cont);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jBtnAgregarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarJugadorMouseClicked
        // TODO add your handling code here:
        if(valFecha()){
        
        llenar();
        limpiar();
        }
    }//GEN-LAST:event_jBtnAgregarJugadorMouseClicked

    private void jTxtJugLocalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtJugLocalKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_SPACE){
        evt.consume();
        }
    }//GEN-LAST:event_jTxtJugLocalKeyTyped

    private void jBtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBtnLimpiarMouseClicked
    
    private void eliminarTabla(int index, JTable tabla){
    
        if(index != -1){
        int mIndex = tabla.convertRowIndexToModel(index);
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            model.removeRow(mIndex);
        }
    }
    
    private void agregarTabla(String nom,String inc,String min,String tiempo, JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        String[] vecto = new String[4];
        vecto[0] = nom;
        vecto[1] = inc;
        vecto[2] = min;
        vecto[3] = tiempo;
        modelo.addRow(vecto);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmResPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmResPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmResPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmResPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmResPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarJugador;
    private javax.swing.JButton jBtnAgregarLocal;
    private javax.swing.JButton jBtnAgregarVisita;
    private javax.swing.JButton jBtnEliminarLocal;
    private javax.swing.JButton jBtnEliminarVisita;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCmbIncLocal;
    private javax.swing.JComboBox jCmbIncVisita;
    private javax.swing.JComboBox jCmbTiempoLocal;
    private javax.swing.JComboBox jCmbTiempoVisita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLocal;
    private javax.swing.JTable jTableVisitante;
    private javax.swing.JTextField jTxtELocal;
    private javax.swing.JTextField jTxtEVisita;
    private javax.swing.JFormattedTextField jTxtFecha;
    private javax.swing.JFormattedTextField jTxtHoraFin;
    private javax.swing.JFormattedTextField jTxtHoraInicio;
    private javax.swing.JTextField jTxtJornada;
    private javax.swing.JTextField jTxtJugLocal;
    private javax.swing.JTextField jTxtJugVisita;
    private javax.swing.JFormattedTextField jTxtMinLocal;
    private javax.swing.JFormattedTextField jTxtMinVisita;
    // End of variables declaration//GEN-END:variables

    private boolean validar(JTextField jugador,JComboBox incidencia,JFormattedTextField minuto, JComboBox tiempo){
    boolean bandera = true;
    String errors="";
   
    if(jugador.getText().equals("") || incidencia.getSelectedIndex() == 0 || minuto.getText().trim().length() == 1 || tiempo.getSelectedIndex() == 0){
    bandera = false;
    
    errors = " Debe llenar todos los campos y seleccionar un item de las cajas de selección\n";
    }
    if(!bandera){
            JOptionPane.showMessageDialog(null, errors,"Los datos de entrada contienen errores de validación",1);
        }
    return bandera;    
    }
   private void limpiar(JTextField jugador,JComboBox incidencia,JFormattedTextField minuto, JComboBox tiempo){
    jugador.setText("");
    incidencia.setSelectedIndex(0);
    minuto.setText("");
    tiempo.setSelectedIndex(0);
   }
   private boolean alreadyInTable(String name, JTable tabla){
       DefaultTableModel model = (DefaultTableModel) tabla.getModel();
       int c = model.getColumnCount();
       int r = model.getRowCount();
       boolean band = true;
       String aux = "";
       ArrayList<String> repe = new ArrayList<String>();
      
       for(int j =0; j<r;j++){
           aux += model.getValueAt(j,0 );
           aux +=model.getValueAt(j,2 );
           aux +=model.getValueAt(j,3 );
           repe.add(aux);
           aux = "";
       }
       for(int i= 0; i< repe.size();i++){
       if(name.toLowerCase().equals(repe.get(i).toLowerCase())){
       band= false;
       JOptionPane.showMessageDialog(rootPane, "El jugador no puede cometer otra incidencia en el mismo minuto en el mismo tiempo","Error",2);
       }
       
       }
       
       
       /*for(int i = 0; i< c;i++){
       for(int j =0; j<r;j++){
       if(name.equals(model.getValueAt(j,i))){
       band= false;
       getToolkit().beep();
       }
       }
       }*/
       return band;
   }

   private boolean valFecha(){
    boolean band = true;
    
    String errores = "";
        int corre = 1;
        final String regex = "^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$";
        if(!this.jTxtFecha.getText().matches(regex)){
        band = false;
        errores += "El formato en el que ingreso la fecha es inválido\n";
        corre++;
        }
    if(!band){
            JOptionPane.showMessageDialog(null, errores,"Los datos de entrada contienen errores de validación",1);
        }
    return band;   
   }
   
   private void llenar(){
       
       if(validarEnviar()){
       Partido p = new Partido(this.jTxtEVisita.getText(), this.jTxtELocal.getText(), this.jTxtJornada.getText(),this.jTxtHoraInicio.getText(),this.jTxtHoraFin.getText(),this.jTxtFecha.getText());
       DefaultTableModel ml = (DefaultTableModel) jTableLocal.getModel();
       DefaultTableModel mv = (DefaultTableModel) jTableVisitante.getModel();
       for(int i = 0; i< ml.getRowCount();i++){
        p.addIncidencia(addIncidencia(ml.getValueAt(i, 0).toString(), ml.getValueAt(i, 2).toString(), ml.getValueAt(i, 3).toString(),ml.getValueAt(i, 1).toString(),"l"));
       }
       for(int i = 0; i< mv.getRowCount();i++){
        p.addIncidencia(addIncidencia(mv.getValueAt(i, 0).toString(), mv.getValueAt(i, 2).toString(), mv.getValueAt(i, 3).toString(),mv.getValueAt(i, 1).toString(),"v"));
       }
       
       p.setScore(this.jTxtELocal.getText(),this.jTxtEVisita.getText());
       
       String mensaje = "Resultado:\n"
               + "Fecha: "+ p.getFecha()
               + "\nHora inicio: " + p.getHora_inicio()
               + "\nHora fin: "+ p.getHora_fin()
               + "\nGanador: "+ p.getGanador()
               + "\nPuntaje: "+ p.getScoreLocal() + " - " + p.getScoreVisita();
       
       
       JOptionPane.showMessageDialog(rootPane, mensaje,"Resultado:",1);
       }
       
       
       
    
   }
   
   private boolean validarEnviar(){
   boolean band = true;
   String errors = "";
   int corre = 1;
    if(this.jTableLocal.getRowCount() == 0 && this.jTableVisitante.getRowCount() == 0){
       band = false;
       errors += "Debe haber almenos una incidencia de tipo gol en algun equipo para poder guardar\n";
        corre++;
       }
    if(thereIsGoals(jTableLocal) && thereIsGoals(jTableVisitante)){
    band = false;
       errors += "Debe haber almenos un equipo con un gol\n";
        corre++;
    }
    
   if(!band){
   JOptionPane.showMessageDialog(rootPane, errors);
   }
   return band;
   }
   
   private boolean thereIsGoals(JTable t){
       boolean band = true;
   DefaultTableModel tab = (DefaultTableModel) t.getModel();
   
   int s = tab.getRowCount();
   for(int i = 0; i< s; i++){
   if( tab.getValueAt(i, 1).toString().toLowerCase().contains("gol")){
   
   band=false;
   }
   
   }
   
   return band;
   }
   private Incidencia addIncidencia(String jugador, String minuto, String tiempo, String tipo,String equipo){
      Incidencia inc= new Incidencia();
       return inc;     
   }
   
private void limpiar(){
this.jTxtFecha.setText("");
this.jTxtHoraInicio.setText("");
this.jTxtHoraFin.setText("");
this.jTxtJugLocal.setText("");
this.jTxtJugVisita.setText("");
this.jCmbIncLocal.setSelectedIndex(0);
this.jCmbIncVisita.setSelectedIndex(0);
this.jTxtMinLocal.setText("");
this.jTxtMinVisita.setText("");
this.jCmbTiempoLocal.setSelectedIndex(0);
this.jCmbTiempoVisita.setSelectedIndex(0);
DefaultTableModel modell = (DefaultTableModel)this.jTableLocal.getModel();
modell.setRowCount(0);
DefaultTableModel modelv = (DefaultTableModel)this.jTableVisitante.getModel();
modelv.setRowCount(0);
}
   

}
