/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esquemasypantallas.frmInternal;

import clases.Entrenador;
import clases.Equipo;
import clases.Utilidades;
import controlador.ControlEquipo;
import controlador.ControlUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class frmModEquipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEquipo
     */
    private Equipo eq;
    public frmModEquipo(Equipo eq) {
        initComponents();
     this.eq = eq;
     jTxtNom.setText(eq.getNombre());
     JTxtDireccion.setText(eq.getDireccion());
     JTxtColor.setText(eq.getColor());
     JTxtEmail.setText(eq.getEmail());
     jTxtTelefono.setText(eq.getTelefono());
     JTxtNumero2.setText(String.valueOf(eq.getNumeroTar()));
       ControlUsuario cu = new ControlUsuario();
        Utilidades util =new Utilidades();
        util.loadCombo(cu.getEntrenadores(), jCmbEnt);
        
        Entrenador ent = (Entrenador) jCmbEnt.getSelectedItem();
    }

    public frmModEquipo(frmModEquipo eq) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblMantEquipo = new javax.swing.JLabel();
        jLblEmailEquipo = new javax.swing.JLabel();
        JTxtEmail = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JLabel();
        JTxtNumero2 = new javax.swing.JTextField();
        jLblIdEntren = new javax.swing.JLabel();
        jIdEquipo4 = new javax.swing.JLabel();
        JTxtDireccion = new javax.swing.JTextField();
        jLbNumero = new javax.swing.JLabel();
        jIdEquipo7 = new javax.swing.JLabel();
        JTxtColor = new javax.swing.JTextField();
        JBtnEliminar = new javax.swing.JButton();
        JBtnGuardar = new javax.swing.JButton();
        jTxtTelefono = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtNom = new javax.swing.JTextField();
        jCmbEnt = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblMantEquipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblMantEquipo.setText("Mantenimiento de Equipo");

        jLblEmailEquipo.setText("Email-Equipo:");

        JTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtEmailActionPerformed(evt);
            }
        });
        JTxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtEmailKeyTyped(evt);
            }
        });

        jTxtEmail.setText("Numero de Tarjetas:");

        JTxtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtNumero2ActionPerformed(evt);
            }
        });
        JTxtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtNumero2KeyTyped(evt);
            }
        });

        jLblIdEntren.setText("Entrenador:");

        jIdEquipo4.setText("Direccion del Equipo:");

        JTxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtDireccionActionPerformed(evt);
            }
        });
        JTxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtDireccionKeyTyped(evt);
            }
        });

        jLbNumero.setText("Telefono Equipo:");

        jIdEquipo7.setText("Color Equipo:");

        JTxtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtColorActionPerformed(evt);
            }
        });
        JTxtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtColorKeyTyped(evt);
            }
        });

        JBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reset.png"))); // NOI18N
        JBtnEliminar.setText("Reset");

        JBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnGuardarMouseClicked(evt);
            }
        });

        try {
            jTxtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+503)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Nombre Equipo");

        jCmbEnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jIdEquipo4)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTxtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jIdEquipo7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLblIdEntren)
                                .addGap(35, 35, 35)
                                .addComponent(jCmbEnt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JBtnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbNumero)
                            .addComponent(jTxtEmail)
                            .addComponent(jLblEmailEquipo)
                            .addComponent(JBtnEliminar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTxtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLblMantEquipo)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblMantEquipo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblIdEntren)
                    .addComponent(jLblEmailEquipo)
                    .addComponent(JTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdEquipo4)
                    .addComponent(JTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmail)
                    .addComponent(JTxtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLbNumero)
                        .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIdEquipo7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnGuardar)
                    .addComponent(JBtnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtEmailActionPerformed

    private void JTxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtEmailKeyTyped
        Character s=evt.getKeyChar();
        if((s<'0'|| s>'9') && (s<'a'||s>'z') && (s<'-'||s>'-') && (s<'@'|| s>'@')&& (s<'.'||s>'.')&& (s<'_'|| s>'_')){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo Ingrese Letras Minusculas, Numeros y Caracteres Especiales -,_,@,.","",1);
        }
    }//GEN-LAST:event_JTxtEmailKeyTyped

    private void JTxtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtNumero2ActionPerformed

    private void JTxtNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtNumero2KeyTyped
        Character s=evt.getKeyChar();
        if(!Character.isDigit(s))
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo Ingrese Numeros","",1);
        }
    }//GEN-LAST:event_JTxtNumero2KeyTyped

    private void JTxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtDireccionActionPerformed

    private void JTxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtDireccionKeyTyped
        Character s=evt.getKeyChar();
        if((s<'0'|| s>'9') && (s<'a'||s>'z') && (s<'-'||s>'-') && (s<'A'|| s>'Z')&& (s<'#'||s>'#')&& s!=KeyEvent.VK_SPACE){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo Ingrese Letras, Numeros y Caracteres Especiales #,-","",1);
        }
    }//GEN-LAST:event_JTxtDireccionKeyTyped

    private void JTxtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtColorActionPerformed

    private void JTxtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtColorKeyTyped
        Character s=evt.getKeyChar();
        if(!Character.isLetter(s) && s!=KeyEvent.VK_SPACE)
        {JOptionPane.showMessageDialog(this, "Solo Ingrese Letras con Espacio","",1);
            evt.consume();
        }
    }//GEN-LAST:event_JTxtColorKeyTyped

    private void JBtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnGuardarMouseClicked
  int op = JOptionPane.showConfirmDialog(rootPane, "Está seguro que desea modificar este Equipo?!",
          "Confirmación",JOptionPane.YES_NO_OPTION);
        if (op == 0) {
             Equipo eq =new Equipo();
              eq = asignar(eq);
        try {

            
                /*String mensaje = "Datos ingresados: \n"+ "Usuario: " + user.getUsuario()+
                "\nContraseña: "+ user.getContra()+
                "\nNombre: "+ user.getNombre()+
                "\nApellido: " + user.getApellido()+
                "\nNivel: " + user.getNivel()+
                "\nDUI: "+ user.getDui()+
                "\nEmail: "+ user.getEmail()+
                "\nTeléfono: "+ user.getTel()+
                "\nFecha Nacimiento: "+ user.getFechaNac();

                JOptionPane.showMessageDialog(this, mensaje, "Resultado",2);*/
                
                ControlEquipo ce = new ControlEquipo();
                JOptionPane.showMessageDialog(this, ce.update(eq));
                
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un nivel de Equipo", "Resultado",1);
        }
            
        }

    }//GEN-LAST:event_JBtnGuardarMouseClicked

    private void jCmbEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JTextField JTxtColor;
    private javax.swing.JTextField JTxtDireccion;
    private javax.swing.JTextField JTxtEmail;
    private javax.swing.JTextField JTxtNumero2;
    private javax.swing.JComboBox<String> jCmbEnt;
    private javax.swing.JLabel jIdEquipo4;
    private javax.swing.JLabel jIdEquipo7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbNumero;
    private javax.swing.JLabel jLblEmailEquipo;
    private javax.swing.JLabel jLblIdEntren;
    private javax.swing.JLabel jLblMantEquipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTxtEmail;
    private javax.swing.JTextField jTxtNom;
    private javax.swing.JFormattedTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables

private Equipo asignar(Equipo eq){
       Entrenador ent = (Entrenador) jCmbEnt.getSelectedItem();
        eq.setIdEntrenador(ent.getIdEnt());
        eq.setEmail(JTxtEmail.getText());
        eq.setDireccion(JTxtDireccion.getText());
        eq.setNumeroTar(Integer.parseInt(JTxtNumero2.getText()));
        eq.setTelefono(jTxtTelefono.getText());
        eq.setColor(JTxtColor.getText());
        eq.setNombre(jTxtNom.getText());
        eq.setIdEq(this.eq.getIdEq());
       
        
        return eq;
}





}
