/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esquemasypantallas.frmInternal;
import clases.*;
import controlador.ControlUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Luis
 */
public class frmModUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUser
     */
    public frmModUser(Usuario u) {
        initComponents();
        this.modUser = u;
      reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAgregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTxtFechaNac = new javax.swing.JFormattedTextField();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPass1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTxtPass2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtDui = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtTel = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jBtnAgregar.setText("Guardar");
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });

        jLabel10.setText("Fecha Nacimiento(dd/m/aaaa)");

        try {
            jTxtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtUsuarioKeyTyped(evt);
            }
        });

        jLabel1.setText("Usuario(máximo 10 caracteres)");

        jTxtPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPass1KeyTyped(evt);
            }
        });

        jLabel2.setText("Contraseña(8 caracteres)");

        jTxtPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPass2KeyTyped(evt);
            }
        });

        jLabel3.setText("Repetir contraseña");

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Nombres");

        jTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyTyped(evt);
            }
        });

        jLabel5.setText("Apellidos");

        try {
            jTxtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("DUI");

        jLabel8.setText("Email");

        try {
            jTxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDui, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtPass2))
                                .addComponent(jTxtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(77, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jBtnAgregar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregar)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked
        // TODO add your handling code here:

        Usuario user =new Usuario();
     
        try {

            asignar(user);
            if(user.validar(jTxtPass2.getText())){
                /*String mensaje = "Datos ingresados: \n"+ "Usuario: " + user.getUsuario()+
                "\nContraseña: "+ user.getContra()+
                "\nNombre: "+ user.getNombre()+
                "\nApellido: " + user.getApellido()+
                "\nNivel: " + user.getNivel()+
                "\nDUI: "+ user.getDui()+
                "\nEmail: "+ user.getEmail()+
                "\nTeléfono: "+ user.getTel()+
                "\nFecha Nacimiento: "+ user.getFechaNac();

                JOptionPane.showMessageDialog(this, mensaje, "Resultado",2);*/
                
                ControlUsuario cu = new ControlUsuario();
                JOptionPane.showMessageDialog(this, cu.update(user));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un nivel de usuario", "Resultado",1);
        }

    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jTxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUsuarioKeyTyped
        // TODO add your handling code here:
        if(this.jTxtUsuario.getText().length() >=10){
            evt.consume();
        }
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtUsuarioKeyTyped

    private void jTxtPass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPass1KeyTyped
        // TODO add your handling code here:

        if(this.jTxtPass1.getText().length() >= 8){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtPass1KeyTyped

    private void jTxtPass2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPass2KeyTyped
        // TODO add your handling code here:
        if(this.jTxtPass2.getText().length() >= 8){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtPass2KeyTyped

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        // TODO add your handling code here:
        char s = evt.getKeyChar();
        if(this.jTxtNombre.getText().length() >=30){
            evt.consume();
        }
        if(Character.isDigit(s) && s != KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyTyped
        // TODO add your handling code here:
        if(this.jTxtApellido.getText().length() >=30){
            evt.consume();
        }
        char s = evt.getKeyChar();
        if(Character.isDigit(s) && s != KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtApellidoKeyTyped

private Usuario asignar(Usuario user){
     user.setFechaNac(jTxtFechaNac.getText());
        user.setEmail(jTxtEmail.getText());
        user.setContra(jTxtPass1.getText());
        user.setNombre(jTxtNombre.getText());
        user.setApellido(jTxtApellido.getText());
        user.setUsuario(jTxtUsuario.getText());
        user.setDui(jTxtDui.getText());
        user.setTel(jTxtTel.getText());
        user.setNivel(this.modUser.getNivel());
        user.setIdUser(this.modUser.getIdUser());
        
        return user;
}    
private void reset(){
  jTxtNombre.setText(this.modUser.getNombre());
        jTxtUsuario.setText(this.modUser.getUsuario());
        jTxtPass1.setText(this.modUser.getContra());
        jTxtPass2.setText(this.modUser.getContra());
        jTxtDui.setText(this.modUser.getDui());
        jTxtEmail.setText(this.modUser.getEmail());
        jTxtTel.setText(this.modUser.getTel());
        jTxtFechaNac.setText(this.modUser.getFechaNac());
        jTxtApellido.setText(this.modUser.getApellido());

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JFormattedTextField jTxtDui;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JFormattedTextField jTxtFechaNac;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JPasswordField jTxtPass1;
    private javax.swing.JPasswordField jTxtPass2;
    private javax.swing.JFormattedTextField jTxtTel;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
    private Usuario modUser;
}
